### ISSUE TITLE
Add command for clearing build task cache

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/tfs-cli#16] opened 2015-08-12 10:58 UTC
It seems like VSO has a cache for build tasks, since if an updated version of the same build task is uploaded to the same tenant, VSO still takes the old version. Even after a Delete and a new Upload.

The only solution at the moment to have changes taking effect during development is by increasing the patch version. This is not ideal since this messes with the released version number (especially if multiple developers work parallel on the same task)

It would be helpful if tfx could provide a command for clearing the build task cache.

**Comment by chrisrpatterson** [comment] 2015-08-12 12:05
During development you can simply setup your own agent and as part of your cycle you can delete the tasks cache on your agent.

**Comment by pascalberger** [comment] 2015-08-12 12:21
Sure, but this would mean that while developing I need to switch over to the agent (which might reside on another machine) everytime I deploy. If there would be a command in tfx I can automatize this.

**Comment by chrisrpatterson** [comment] 2015-08-12 12:26
The problem is the cache is on each agent and the server does not maintain that state.  The agent uses the version information (sort of like npm or nuget packages) to know what it needs to download.  For my I simply setup an agent on my devbox for this type of work.

**Comment by bryanmacfarlane** [comment] 2015-08-12 12:29
We have something similar on our backlog.  The server sends messages to the agent for things like build.  we have other messages like cancel your build.  We want a reset action from the admin web UI.  Once that's in and there's a REST api to trigger, we could add to the CLI.

Moving to our backlog

**Closed by bryanmacfarlane** 2015-08-12 12:29 UTC

**Comment by fredgate** [comment] 2016-05-19 14:48
Is this issue resolved ?
May be that when we are doing a upload by forcing an overwrite, the server should notify the agents to clear the cache for this version of the task.
  tfs build taks upload --overwrite

**Comment by bryanmacfarlane** [comment] 2016-05-19 14:51
No, it's by design.

The version is an immutable identifier of that version of the code.  If you changed the code, then you should bump the version.
