### ISSUE TITLE
Extension package is malformed/corrupted

### ISSUE THREAD

**Issue by yahavi** [microsoft/tfs-cli#339] opened 2020-04-02 10:15 UTC
I'm using `tfx extension publish` to publish my extension to Azure DevOps marketplace.
Publishing with tfx-cli 0.6.4 works fine.
With 0.7.4 and above I'm getting an unclear error message:
`error: Extension package is malformed/corrupted`:
![image](https://user-images.githubusercontent.com/11367982/78237184-a43bc480-74e3-11ea-88cd-6fac62e01a69.png)

I couldn't find any problems in my extension. Without any logs information I can't even know where to start looking.
How can I get more information about this error?

I'm using MacOS.

Thanks.

**Comment by azlam-abdulsalam** [comment] 2020-04-24 23:15
I am having the same issue, I noticed the package created is able to be published through the UI. Any updates?

**Comment by jflinchbaugh** [comment] 2020-05-27 19:01
How big is the vsix file? I've had this problem when my package grew beyond 19MB. tfx-cli saw this same error, but website would still accept the extension.  This link led me to reproduce and prove the 19MB limit: https://developercommunity.visualstudio.com/content/problem/668297/size-limit-to-publish-azure-devops-pipelines-custo.html

**Comment by yahavi** [comment] 2020-05-31 05:49
@jflinchbaugh yes, I can approve that TFS CLI cannot publish my extension if it above 19MB.
However, In the documentation under [Check package size](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#check-package-size), it is mentioned explicitly that:
> Check the size of the vsix after it is packaged. If greater than 50 MB then it needs to be optimized.

For me it looks like an issue with TFS CLI or Azure DevOps REST API.
Can someone from the TFS CLI team take a look at this issue?
Thanks!

**Comment by mburumaxwell** [comment] 2020-12-10 08:30
Facing the same issue. Is there a workaround, other than reducing size?

**Comment by KinsonDigital** [comment] 2021-01-26 16:50
I am facing the same issue as well.  With the documentation clearly stating that we are allowed to be 50MB or less and marketplace web UI accepting the package with no issues, I think this should be fixed.  This might be needed by various release pipelines as well.

**Comment by KinsonDigital** [comment] 2021-01-26 16:52
> How big is the vsix file? I've had this problem when my package grew beyond 19MB. tfx-cli saw this same error, but website would still accept the extension. This link led me to reproduce and prove the 19MB limit: https://developercommunity.visualstudio.com/content/problem/668297/size-limit-to-publish-azure-devops-pipelines-custo.html

I also think this is strange.  The ticket says it was fixed with an update and I am pretty sure that I have the latest tfx-cli version, and this github issue is still open.

**Comment by nexsodev** [comment] 2021-03-18 10:59
Same here....

**Comment by arashi01** [comment] 2021-03-25 07:24
> How big is the vsix file? I've had this problem when my package grew beyond 19MB. tfx-cli saw this same error, but website would still accept the extension. This link led me to reproduce and prove the 19MB limit: https://developercommunity.visualstudio.com/content/problem/668297/size-limit-to-publish-azure-devops-pipelines-custo.html

I just faced this issue trying to publish to marketplace with tfx-cli 0.9.0. 

Also took a lot of searching to find this thread. It would be great if at least the error message was more specific and indicated the issue is package size at least.

**Comment by RobiNino** [comment] 2021-04-07 07:29
This issue is really limiting our development and release process.
Any intention to fix it?

**Comment by dwilsonactual** [comment] 2021-04-19 12:29
The problem with uploading large vsix files has been fixed. The problem was server-side so there is no need to update tfx.

**Closed by dwilsonactual** 2021-04-19 12:29 UTC

**Comment by wjdavis5** [comment] 2021-06-15 15:08
Hello, wanted to check on this as it will be blocking us pretty soon.

**Comment by dwilsonactual** [comment] 2021-06-16 15:13
@wjdavis5 sorry for the difficulty, I've created a bug on the team that owns the responsible service. You can increase visibility by providing feedback at https://developercommunity.visualstudio.com/search?space=21

**Comment by wjdavis5** [comment] 2021-07-13 11:59
Can you link the bug you created please?

**Comment by dwilsonactual** [comment] 2021-07-13 19:43
@wjdavis5 unfortunately the bug is on an internal project. The best way to get in contact with the responsible team would be by opening an issue at https://developercommunity.visualstudio.com/search?space=21

**Comment by wnbittle** [comment] 2021-08-24 20:18
I'm also seeing this issue (0.9.2) 40 MB extension giving "error: Extension package is malformed/corrupted".  The UI accepts it without error.  I've opened the following issue:

https://developercommunity.visualstudio.com/t/Extension-package-is-malformedcorrupted/1512680?space=21&entry=myfeedback

**Comment by wnbittle** [comment] 2021-09-23 21:25
For what it's worth, I eventually got webpack to work so this is no longer a blocker for me.  For details look at this thread https://github.com/microsoft/azure-pipelines-task-lib/issues/667

**Comment by v-shameerms** [comment] 2024-09-27 07:25
Hi All

If you are having issue with Publishing the extension with large package size, please reach out to VSMarketplace@microsoft.com.

Thanks
