### ISSUE TITLE
Update agent packages on tfs

### ISSUE THREAD

**Issue by titans2016** [microsoft/tfs-cli#146] opened 2016-09-09 14:08 UTC
Hi.
We have TFS 2015 on premise.
We discoverev, that on github we can download new version of agent.
Can we upload new agent version to tfs, that we will download from tfs?

**Comment by AnnaOpareva** [comment] 2021-09-07 11:00
Hi, @titans2016 again. Is it still an actual issue for you?

**Comment by titans2016** [comment] 2021-09-07 11:03
No

вторник, 7 сентября 2021 г., 14:00 +0300 от ***@***.***  ***@***.***>:

**Comment by AnnaOpareva** [comment] 2021-09-09 12:12
I am closing this item since the issue is not actual anymore.

**Closed by AnnaOpareva** 2021-09-09 12:12 UTC
Labels: question, Area: tfx-cli

**Comment by anatolybolshakov** [comment] 2021-09-09 12:31
Hi @titans2016 you can install updated agent for TFS 2015 - for this you need to set up AZP_AGENT_DOWNGRADE_DISABLED environment variable to 'true' before configuration - to avoid agent downgrade to default agent version for the server.
