### ISSUE TITLE
Uploading of Azure DevOps Extensions fails with timeout

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/tfs-cli#408] opened 2022-04-19 15:12 UTC
See: https://github.com/microsoft/azure-devops-extension-tasks/issues/219

```
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\tfx\0.10.0\x64\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.110.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"
 0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\hostedtoolcache\\windows\\tfx\\0.10.0\\x64\\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.110.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"\r',
  '' ]
 1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\hostedtoolcache\\windows\\tfx\\0.10.0\\x64\\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.110.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"\r',
  '' ]
error: Request timeout: /_apis/gallery/publishers/jessehouwing/extensions/vsts-developer-tools-build-tasks-dev 0 [ 'error: Request timeout: /_apis/gallery/publishers/jessehouwing/extensions/vsts-developer-tools-build-tasks-dev',
  '' ]
 1 [ 'error: Request timeout: /_apis/gallery/publishers/jessehouwing/extensions/vsts-developer-tools-build-tasks-dev',
  '' ]
```

After the timeout, it seems the extension is partially uploaded to the marketplace, because attempting to re-upload the extension fails with a different error message:

```
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\tfx\0.11.0\x64\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.111.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"
 0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\hostedtoolcache\\windows\\tfx\\0.11.0\\x64\\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.111.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"\r',
  '' ]
 1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\hostedtoolcache\\windows\\tfx\\0.11.0\\x64\\tfx.cmd extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix jessehouwing.vsts-developer-tools-build-tasks-dev-3.1.111.gen.vsix --share-with jessehouwing-dev --no-wait-validation --debug-log-stream stderr"\r',
  '' ]
error: The extension already exists. 0 [ 'error: The extension already exists.', '' ]
 1 [ 'error: The extension already exists.', '' ]
```

I've tried multiple hosts to publish the extension from, incl the Azure Pipelines hosted pool. All fail.

**Comment by jessehouwing** [comment] 2022-04-25 08:00
After the marketplace team did a few interventions on the backend, pushing large extensions or working again as expected.

**Comment by max-zaytsev** [comment] 2022-04-29 08:59
@jessehouwing Thanks for reporting! Did I understand correctly that the problem is solved?
Can I close this now?

**Closed** 2022-04-29 09:08 UTC
Labels: Area: tfx-cli, triage
